"""Week-15 W-C: Wilson 95% intervals for every RULER cell in the decision table.

Strictly read-only over ``results/``. RULER is all-or-nothing per trial, and
``results/w11-decision-table.json`` stores each cell's pooled accuracy PLUS its
exact trial count (``n_<task>``), so the hit count is recoverable exactly as
``hits = round(acc * n)`` -- the same recovery ``w11_merge.py`` (:77-83) uses to
pool. Every (ctx, method, task) cell gets a Wilson 95% score interval. Emits:

- ``results/w15-ruler-intervals.json``  -- acc / n / hits / lo / hi per cell
- ``results/w15-ruler-intervals.md``    -- compact method x ctx x task table

``w11_merge.py`` and the decision table are never modified; re-run this after
any merge to refresh the intervals. Interpretation lives in
``docs/week15-significance.md``.

    uv run python scripts/w15_intervals.py
"""

from __future__ import annotations

import json
import math
from pathlib import Path
from typing import Any

from w11_merge import ORDER, TASKS

TABLE = Path("results/w11-decision-table.json")
OUT_JSON = Path("results/w15-ruler-intervals.json")
OUT_MD = Path("results/w15-ruler-intervals.md")
Z95 = 1.959963984540054  # two-sided 95% normal quantile

# Sanity cells printed on every run (pre-registered shapes, not new claims):
#   - an 8/8 cell must land in the [0.676, 1.0] region;
#   - shadow-r64 32K cells are 0/2 -> wide [0, 0.658] (and VOID anyway: the
#     attach-scope harness bug, Week-15 W-A re-measures them).
# bugSseed-r32-h256@16K mk is 8/8 in results/w14-wseed8-ruler-lines.txt but is
# NOT yet in the decision table (w11_merge.RULER_LOGS stops at Week-12), so it
# prints as missing until that merge lands.
SANITY = [
    ("16384", "bugSseed-r32-h256", "niah_multikey"),
    ("16384", "full", "niah_multikey"),
    ("32768", "shadow-r64", "niah_multikey"),
    ("32768", "shadow-r64", "vt"),
]

TASK_LABEL = {
    "niah_single": "needle",
    "niah_multikey": "multi-key",
    "niah_multivalue": "multi-value",
    "vt": "var-track",
}


def wilson(hits: int, n: int, z: float = Z95) -> tuple[float, float]:
    """Wilson score interval for ``hits`` successes in ``n`` Bernoulli trials."""
    if n <= 0 or not 0 <= hits <= n:
        raise ValueError(f"bad cell: hits={hits} n={n}")
    p = hits / n
    z2 = z * z
    denom = 1.0 + z2 / n
    center = (p + z2 / (2 * n)) / denom
    half = (z / denom) * math.sqrt(p * (1.0 - p) / n + z2 / (4.0 * n * n))
    return max(0.0, center - half), min(1.0, center + half)


def build(table: dict[str, dict[str, dict[str, float]]]) -> dict[str, Any]:
    """Intervals for every (ctx, method, task) cell that has both acc and n."""
    cells: dict[str, dict[str, dict[str, dict[str, float | int]]]] = {}
    for ctx in sorted(table, key=int):
        for method, row in table[ctx].items():
            for task in TASKS:
                if task not in row or f"n_{task}" not in row or row[task] is None:
                    continue
                a, n = float(row[task]), int(row[f"n_{task}"])
                hits = round(a * n)
                # acc must be hits/n up to the table's 4dp rounding -- anything
                # else means the stored n does not belong to this acc.
                if abs(a * n - hits) > 0.01:
                    raise ValueError(f"non-integral hits at {ctx}/{method}/{task}: {a}*{n}")
                lo, hi = wilson(hits, n)
                cells.setdefault(ctx, {}).setdefault(method, {})[task] = {
                    "acc": a,
                    "n": n,
                    "hits": hits,
                    "lo": round(lo, 4),
                    "hi": round(hi, 4),
                }
    return {
        "meta": {
            "source": str(TABLE),
            "interval": "wilson",
            "z": Z95,
            "note": "hits = round(acc * n), exact for the all-or-nothing RULER "
            "metric (w11_merge.py:77-83); lo/hi are fractions in [0, 1]",
        },
        "cells": cells,
    }


def _method_order(methods: list[str]) -> list[str]:
    known = [m for m in ORDER if m in methods]
    return known + sorted(m for m in methods if m not in known)


def fmt_md(blob: dict[str, Any]) -> str:
    out = [
        "# Week-15: Wilson 95% intervals for every RULER cell",
        "",
        f"Source: `{blob['meta']['source']}` (read-only). Cell format: "
        "`acc% [lo, hi] (hits/n)`. Generated by `scripts/w15_intervals.py`; "
        "interpretation in `docs/week15-significance.md`.",
        "",
        "NOTE: shadow-* rows are VOID pending the Week-15 W-A attach-scope "
        "re-measure (harness bug, see the week-15 plan); intervals are shown "
        "for completeness.",
    ]
    for ctx, methods in blob["cells"].items():
        out.append(f"\n## {int(ctx) // 1024}K context\n")
        out.append("| method | " + " | ".join(TASK_LABEL[t] for t in TASKS) + " |")
        out.append("|---|" + "---|" * len(TASKS))
        for m in _method_order(list(methods)):
            row = methods[m]
            parts = []
            for t in TASKS:
                c = row.get(t)
                if c is None:
                    parts.append("—")
                else:
                    parts.append(
                        f"{100 * c['hits'] / c['n']:.1f} "
                        f"[{100 * c['lo']:.1f}, {100 * c['hi']:.1f}] "
                        f"({c['hits']}/{c['n']})"
                    )
            out.append(f"| {m} | " + " | ".join(parts) + " |")
    return "\n".join(out) + "\n"


def main() -> None:
    blob = build(json.loads(TABLE.read_text()))
    OUT_JSON.write_text(json.dumps(blob, indent=2) + "\n")
    OUT_MD.write_text(fmt_md(blob))
    n_cells = sum(len(r) for ms in blob["cells"].values() for r in ms.values())
    print(f"[w15-intervals] {n_cells} cells -> {OUT_JSON} + {OUT_MD}")
    for ctx, method, task in SANITY:
        cell = blob["cells"].get(ctx, {}).get(method, {}).get(task)
        if cell is None:
            print(
                f"[sanity] {method}@{int(ctx) // 1024}K {task}: NOT in "
                f"{TABLE.name} (not yet merged by w11_merge.py)"
            )
            continue
        print(
            f"[sanity] {method}@{int(ctx) // 1024}K {task}: "
            f"{cell['hits']}/{cell['n']} = {100 * cell['acc']:.1f}% "
            f"[{100 * cell['lo']:.1f}, {100 * cell['hi']:.1f}]"
        )


if __name__ == "__main__":
    main()
